name: make_docs

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
       - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Set up Python 3.8 environment
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      
      # Cache dependencies
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          path: ~/.cache/pip
      
      # Install MkDocs Material and necessary plugins
      - run: pip install mkdocs-material mkdocs-jupyter

      # Optional: If you have other dependencies, install them here
      - run: pip install pillow cairosvg # install any additional plugins
      
      # Copy your notebooks to the docs folder
      - run: cp python_basics.ipynb docs/
      
      # Deploy your site to GitHub Pages
      - run: mkdocs gh-deploy --force
